### ISSUE TITLE
End time of consecutive time entries does not line up

### ISSUE THREAD

**Issue by Mikael-MStinson** [Mikael-MStinson/Time-Calculator#3]
>202 off 217 on 225 off 239 on 241
start time: 202, end time: 240, deduct: 0.48, total: 0.16000000000000003

End time should be 241, not 240

**Comment by Mikael-MStinson** [comment]
Changing calculate_time's output from a round to a math.ceil, I get the following failure report:
`PS H:\Documents\Git\Time-Calculator> python -m unittest discover
.......FF.....FFF..F...............
======================================================================
FAIL: test_half_hour (tests.TestCalculateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "H:\Documents\Git\Time-Calculator\tests.py", line 17, in test_half_hour
    self.assertEqual(calculate_time(900,930), 0.5)
AssertionError: 1 != 0.5

======================================================================
FAIL: test_odd_hours (tests.TestCalculateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "H:\Documents\Git\Time-Calculator\tests.py", line 29, in test_odd_hours
    self.assertEqual(calculate_time(1011,1042), 0.52)
AssertionError: 1 != 0.52

======================================================================
FAIL: test_bug_1 (tests.TestCombineAndDeductTimeEntries)
End time is invalid hour values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "H:\Documents\Git\Time-Calculator\tests.py", line 112, in test_bug_1
    self.assertEqual(combine_and_deduct_time_entries("945 off 1016 on 1112 1234 on 1249"),(945,1127,0.52,1.18))
AssertionError: Tuples differ: (945, 1245, 1, 2) != (945, 1127, 0.52, 1.18)

First differing element 1:
1245
1127

- (945, 1245, 1, 2)
+ (945, 1127, 0.52, 1.18)

======================================================================
FAIL: test_bug_2 (tests.TestCombineAndDeductTimeEntries)
Actual Hours Discrepancy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "H:\Documents\Git\Time-Calculator\tests.py", line 116, in test_bug_2
    self.assertEqual(combine_and_deduct_time_entries("1112 off 1124 on 1155 off 1215 1249 on 1258"),(1112,1224,0.53,0.67))
AssertionError: Tuples differ: (1112, 312, 2, 2) != (1112, 1224, 0.53, 0.67)

First differing element 1:
312
1224

- (1112, 312, 2, 2)
+ (1112, 1224, 0.53, 0.67)

======================================================================
FAIL: test_bug_3 (tests.TestCombineAndDeductTimeEntries)
End time of consecutive time entries does not line up
----------------------------------------------------------------------
Traceback (most recent call last):
  File "H:\Documents\Git\Time-Calculator\tests.py", line 120, in test_bug_3
    self.assertEqual(combine_and_deduct_time_entries("202 off 217 on 225 off 239 on 241"),(202,241,0.48,0.17))
AssertionError: Tuples differ: (202, 602, 2, 2) != (202, 241, 0.48, 0.17)

First differing element 1:
602
241

- (202, 602, 2, 2)
+ (202, 241, 0.48, 0.17)

======================================================================
FAIL: test_non_consecutive_time_entries (tests.TestCombineAndDeductTimeEntries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "H:\Documents\Git\Time-Calculator\tests.py", line 108, in test_non_consecutive_time_entries
    self.assertEqual(combine_and_deduct_time_entries("1000 on 1100 off 100 on 200 300 on 430"),(1000,330,2.0,3.5))
AssertionError: Tuples differ: (1000, 400, 2, 4) != (1000, 330, 2.0, 3.5)

First differing element 1:
400
330

- (1000, 400, 2, 4)
+ (1000, 330, 2.0, 3.5)

----------------------------------------------------------------------
Ran 35 tests in 0.010s

FAILED (failures=6)`

**Comment by Mikael-MStinson** [comment]
A test has been added, this has been confirmed to be an issue.
We are adding 0.64 hours to 202. This equates to 38.4 minutes, but it needs to be rounded up to 39.
Somewhere in add_hours_to_time I need to apply a math.ceil function to the minutes element.
I'll need to tinker with that some more, for now the changes made to address this issue are being committed without resolving the issue.

**Comment by Mikael-MStinson** [comment]
Addressed in the latest commit
